---
- hosts: webserver
  become: true
  tasks:
    - name: install components
      apt: 
        state: present
        update_cache: yes
        pkg:
          - apache2
          - libapache2-mod-wsgi
          - python3
          
    - name: ensure apache is started
      service: name=apache state=started enabled=yes