---
- hosts: webserver
  become: true
  tasks:
    - name: install components
      apt: 
        state: present
        update_cache: yes
        pkg:
          - apache2
          - libapache2-mod-wsgi
          - python3

    - name: ensure apache is started
      service: name=apache2 state=started enabled=yes

    - name: ensure mod_wsgi is started
      apache2_module: state=present name=wsgi
      notify: restart apache2
    
  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted