---
- hosts: webserver
  become: true
  tasks:
    - name: install apache2
      apt: 
        state: present
        update_cache: yes
        pkg:
          - apache2
          - libapache2-mod-wsgi
          - python3
          - python_pip
          - python_virtualenv